### ISSUE TITLE
Compatibility with Bevy 0.8

### ISSUE THREAD

**Issue by djrakita** [nilclass/bevy_stl#7]
It would be great if `bevy_stl` could be updated to officially support bevy 0.8.  I would provide a pull request that has this done already, but I must've done something wrong when I tried - my fork has the spinning disc example working just fine in 0.8, but when I try to use this fork in other projects, I get the following error:

```string
ERROR bevy_render::mesh::mesh: Invalid attribute format for Vertex_Uv. Given format is Float32x3 but expected Float32x2
```

When I saw that, I figured I would leave this to the people who know more about bevy/ bevy_stl than me :)

Thanks

**Comment by nilclass** [comment]
@djrakita thanks for reporting this!

Are you using the Wireframe feature by any chance? The Float32x3 vs Float32x2 issue was fixed for the regular mesh [in an earlier PR](https://github.com/nilclass/bevy_stl/pull/4/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R90), but is not fixed for the wireframe.

Changing [this line](https://github.com/nilclass/bevy_stl/blob/9152fd67a67f7ec97fc2e6a3d7283afc9148ff49/src/lib.rs#L120) to use Float32x2 should do the trick.

Feel free to give it a try and submit a PR - otherwise I'll do it once I find the time :smile:
